import { Redirect, useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Image, Keyboard, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '@/constants/tokens';
import { useAuth } from '@/lib/auth';
import { ApiError } from '@/lib/api';

export default function LoginScreen() {
  const { user, signIn } = useAuth();
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [otp, setOtp] = useState('');
  const [mfaRequired, setMfaRequired] = useState(false);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  if (user) return <Redirect href={user.must_change_password || user.privacy_acknowledgment_required ? '/onboarding' : '/(tabs)'} />;
  const submit = async () => { Keyboard.dismiss(); setBusy(true); setError(''); try { await signIn(email.trim(), password, otp); } catch (reason) { const data = reason instanceof ApiError ? reason.data as { code?: string } : undefined; if (data?.code === 'mfa_required') { setMfaRequired(true); setError('Enter the code from your authenticator app or a recovery code.'); } else setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.layout}><View style={styles.brand}><Image source={require('../../assets/images/school_logo.png')} style={styles.logo} accessibilityLabel="Talavera Senior High School" /><View style={styles.brandText}><Text style={styles.brandName}>TALA-AI</Text><Text style={styles.brandCaption}>Talavera Senior High School</Text></View></View><View style={styles.form}><Text style={styles.title}>Student sign in</Text><Text style={styles.description}>Access your recovery activities, assessments, and progress updates.</Text>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Text style={styles.label}>School email</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email" /><Text style={styles.label}>Password</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry autoComplete="current-password" />{mfaRequired && <><Text style={styles.label}>Verification code</Text><TextInput style={styles.input} value={otp} onChangeText={setOtp} keyboardType="number-pad" autoCapitalize="none" autoFocus placeholder="6-digit or recovery code" /></>}<Pressable onPress={() => router.push('/forgot-password')} accessibilityRole="link"><Text style={styles.forgot}>Forgot password?</Text></Pressable><Pressable style={({ pressed }) => [styles.button, pressed && styles.pressed, busy && styles.disabled]} onPress={submit} disabled={busy || (mfaRequired && !otp.trim())}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>{mfaRequired ? 'Verify and sign in' : 'Sign in'}</Text>}</Pressable><Text style={styles.notice}>Use only your assigned school account. Activity and assessment progress is recorded.</Text></View></KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, layout: { flex: 1, padding: spacing.xl, justifyContent: 'center' }, brand: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.xxl }, logo: { width: 48, height: 48, resizeMode: 'contain' }, brandText: { flex: 1 }, brandName: { fontSize: 18, color: colors.text, fontWeight: '800' }, brandCaption: { color: colors.secondaryText, fontSize: 12 }, form: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel, padding: spacing.xl }, title: { fontSize: 24, fontWeight: '700', color: colors.text }, description: { color: colors.secondaryText, lineHeight: 20, marginTop: spacing.sm, marginBottom: spacing.xl }, label: { color: colors.text, fontSize: 13, fontWeight: '600', marginBottom: spacing.sm }, input: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.control, minHeight: 48, paddingHorizontal: spacing.lg, color: colors.text, backgroundColor: '#fff', marginBottom: spacing.lg }, forgot: { color: colors.primary, fontWeight: '700', textAlign: 'right', marginTop: -spacing.sm, marginBottom: spacing.md }, button: { minHeight: 48, borderRadius: radius.control, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm }, buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 }, notice: { color: colors.secondaryText, fontSize: 12, lineHeight: 18, marginTop: spacing.lg }, error: { color: colors.error, backgroundColor: '#fef3f2', borderRadius: radius.control, padding: spacing.md, marginBottom: spacing.lg }, pressed: { opacity: .85 }, disabled: { opacity: .6 } });
