server {
    listen 80;
    server_name _;
    client_max_body_size 500m;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /protected-media/ {
        internal;
        alias /srv/media/;
        add_header X-Content-Type-Options nosniff always;
    }

    location /static/ {
        alias /srv/static/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
