# Generated by Django 5.2.17 on 2026-08-27 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('grade_level', models.PositiveSmallIntegerField()),
                ('school_year', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'academic classes',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='recovery.academicclass'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher / ARAL Tutor'), ('admin', 'Administrator')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='recovery.academicclass')),
                ('assigned_classes', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='recovery.academicclass')),
                ('assigned_subjects', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='recovery.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tala_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
