# Generated by Django 5.2.17 on 2026-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0006_academicclass_is_active_competency_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_pending_secret',
            field=models.TextField(blank=True),
        ),
    ]
