# Generated by Django 5.2.17 on 2026-08-29 02:57

import django.db.models.deletion
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


def index_existing_resources(apps, schema_editor):
    LearningResource = apps.get_model('recovery', 'LearningResource')
    LearningResourceChunk = apps.get_model('recovery', 'LearningResourceChunk')
    for resource in LearningResource.objects.filter(is_approved=True):
        content = (resource.content or '').strip()
        if not content:
            continue
        keywords = sorted(set(re.findall(r'[a-z0-9]+', f'{resource.title} {content}'.casefold())))[:80]
        LearningResourceChunk.objects.create(resource=resource, position=1, heading=resource.title, content=content[:4000], locator=resource.original_filename or 'Approved TALA lesson', keywords=keywords)


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0008_userprofile_address_line_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='grounding_status',
            field=models.CharField(default='grounded', max_length=24),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='source_citations',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='LearnerCompetencyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('diagnostic', 'Diagnostic assessment'), ('practice', 'Recovery practice'), ('mastery', 'Mastery assessment'), ('intervention', 'Teacher intervention')], max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.PositiveIntegerField()),
                ('summary', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_evidence', to='recovery.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'competency', 'evidence_type', 'source_type', 'source_id'), name='unique_learner_competency_evidence_source')],
            },
        ),
        migrations.CreateModel(
            name='LearningResourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=240)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='recovery.learningresource')),
            ],
            options={
                'ordering': ['resource_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'position'), name='unique_resource_chunk_position')],
            },
        ),
        migrations.RunPython(index_existing_resources, migrations.RunPython.noop),
    ]
