# Generated by Django 5.2.17 on 2026-08-30 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0019_backfill_recovery_recommendation_rationale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialexamconsent',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialexamconsent',
            name='identity_verification_method',
            field=models.CharField(default='verified_email_link', max_length=40),
        ),
        migrations.AddField(
            model_name='remedialexamconsent',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialexamconsent',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedialexamconsent',
            name='status',
            field=models.CharField(choices=[('requested', 'Awaiting parent/guardian'), ('approved', 'Approved'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='requested', max_length=16),
        ),
        migrations.CreateModel(
            name='AIMessageEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grounding_accurate', models.BooleanField()),
                ('hallucination_detected', models.BooleanField(default=False)),
                ('incorrect_answer_leakage', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='recovery.aimessage')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_message_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('correction', 'Correction'), ('export', 'Export'), ('deletion', 'Deletion')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('completed', 'Completed'), ('denied', 'Denied')], default='open', max_length=12)),
                ('details', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchEvaluationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('algorithm_version', models.CharField(default='evidence-rank-v1', max_length=80)),
                ('dataset_version', models.CharField(max_length=80)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('record_counts', models.JSONField(default=dict)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_evaluation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frozen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsabilityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=40)),
                ('participant_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=12)),
                ('task_name', models.CharField(max_length=180)),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partially completed'), ('failed', 'Failed')], max_length=12)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('sus_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_usability_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
