# Generated by Django 5.2.17 on 2026-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0020_remedialexamconsent_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='consent_expiry_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='consent_policy_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='consent_policy_version',
            field=models.CharField(default='DRAFT-1', max_length=40),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='minor_data_retention_days',
            field=models.PositiveIntegerField(default=1825),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='privacy_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
