# Generated by Django 5.2.17 on 2026-08-30 12:44

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


def populate_class_codes(apps, schema_editor):
    AcademicClass = apps.get_model('recovery', 'AcademicClass')
    for academic_class in AcademicClass.objects.filter(class_code__isnull=True):
        code = secrets.token_hex(4).upper()
        while AcademicClass.objects.filter(class_code=code).exists():
            code = secrets.token_hex(4).upper()
        academic_class.class_code = code
        academic_class.save(update_fields=['class_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0026_learning_assignment_tala_conversations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='class_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(populate_class_codes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='systemconfiguration',
            name='privacy_notice_text',
            field=models.TextField(default="I acknowledge that TALA-AI records my account details, learning activities, assessment results, and recovery progress for the school's ARAL academic support program. I understand that I may contact the school to request access or correction of my information."),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='privacy_notice_version',
            field=models.CharField(default='TALA-PRIVACY-1', max_length=40),
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('source', models.CharField(choices=[('student', 'Student class code'), ('teacher', 'Teacher enrollment'), ('admin', 'Administrator override')], max_length=12)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='recovery.academicclass')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'academic_class'), name='unique_pending_class_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=40)),
                ('declaration_text', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('response_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'policy_version'), name='unique_user_privacy_acknowledgment')],
            },
        ),
    ]
