# Generated by Django 5.2.17 on 2026-08-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classify_legacy_resources(apps, schema_editor):
    LearningResource = apps.get_model('recovery', 'LearningResource')
    LearningResource.objects.filter(file='', external_url='').update(purpose='recovery')


def restore_legacy_resources(apps, schema_editor):
    LearningResource = apps.get_model('recovery', 'LearningResource')
    LearningResource.objects.filter(purpose='recovery', file='', external_url='').update(purpose='regular')


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0027_academicclass_class_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='prerequisite_assignments',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for_assessments', to='recovery.learningassignment'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='purpose',
            field=models.CharField(choices=[('regular', 'Regular class material'), ('prerequisite', 'Required before diagnostic'), ('recovery', 'Recovery/remediation material'), ('enrichment', 'Enrichment material')], default='regular', max_length=16),
        ),
        migrations.RunPython(classify_legacy_resources, restore_legacy_resources),
        migrations.AddField(
            model_name='practicequestion',
            name='provenance',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('ai', 'AI generated'), ('manual', 'Manually authored')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='source_locator',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='question',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='source_resources',
            field=models.ManyToManyField(blank=True, related_name='grounded_assessment_questions', to='recovery.learningresource'),
        ),
        migrations.CreateModel(
            name='AssessmentEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recommended', 'Recommended for teacher review'), ('eligible', 'Eligible'), ('exempted', 'Not required'), ('completed', 'Completed')], default='recommended', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='recovery.assessment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_assessment_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='unique_assessment_student_eligibility')],
            },
        ),
    ]
