# Generated by Django 5.2.17 on 2026-08-30 18:21

from django.db import migrations, models


def backfill_student_grades(apps, schema_editor):
    StudentProfile = apps.get_model('recovery', 'StudentProfile')
    for details in StudentProfile.objects.select_related('profile__academic_class'):
        academic_class = details.profile.academic_class
        if academic_class and details.grade_level != academic_class.grade_level:
            details.grade_level = academic_class.grade_level
            details.save(update_fields=['grade_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0028_assessment_prerequisite_assignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.RunPython(backfill_student_grades, migrations.RunPython.noop),
    ]
