# Generated by Django 5.2.17 on 2026-08-31 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0030_normalize_video_resource_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentrequest',
            name='unique_pending_class_enrollment',
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_requests', to='recovery.subject'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'academic_class', 'subject'), name='unique_pending_subject_class_enrollment'),
        ),
    ]
