# Generated by Django 5.2.17 on 2026-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0032_remove_general_mathematics_from_grade_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator')], max_length=12),
        ),
    ]
