# Generated by Django 5.2.17 on 2026-08-31 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def normalize_duplicate_active_plans(apps, schema_editor):
    RecoveryPlan = apps.get_model("recovery", "RecoveryPlan")
    duplicates = RecoveryPlan.objects.filter(status="active").values("student_id", "competency_id").annotate(total=Count("id")).filter(total__gt=1)
    for duplicate in duplicates:
        plans = RecoveryPlan.objects.filter(status="active", student_id=duplicate["student_id"], competency_id=duplicate["competency_id"]).order_by("created_at", "id")
        plans.exclude(pk=plans.first().pk).update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("recovery", "0033_alter_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICompanionSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goal", models.CharField(blank=True, max_length=240)),
                ("stage", models.CharField(choices=[("orient", "Set the learning goal"), ("explain", "Understand the concept"), ("example", "Review an example"), ("reasoning", "Explain your reasoning"), ("practice", "Try independent practice"), ("reflect", "Reflect and summarize"), ("completed", "Completed")], default="orient", max_length=16)),
                ("summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIHelpRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField()),
                ("status", models.CharField(choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved")], default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(model_name="recoveryplan", name="trigger_attempt", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_recovery_plans", to="recovery.assessmentattempt")),
        migrations.AddField(model_name="recoveryplan", name="trigger_status", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="systemconfiguration", name="developing_support_policy", field=models.CharField(choices=[("monitor", "Monitor only"), ("guided", "Guided support plan"), ("full", "Full recovery plan")], default="guided", max_length=16)),
        migrations.RunPython(normalize_duplicate_active_plans, migrations.RunPython.noop),
        migrations.AddConstraint(model_name="recoveryplan", constraint=models.UniqueConstraint(condition=models.Q(("status", "active")), fields=("student", "competency"), name="unique_active_student_competency_plan")),
        migrations.AddField(model_name="aicompanionsession", name="conversation", field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="companion_session", to="recovery.aiconversation")),
        migrations.AddField(model_name="aicompanionsession", name="student", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="companion_sessions", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="aihelprequest", name="competency", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_help_requests", to="recovery.competency")),
        migrations.AddField(model_name="aihelprequest", name="plan", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="help_requests", to="recovery.recoveryplan")),
        migrations.AddField(model_name="aihelprequest", name="session", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="help_requests", to="recovery.aicompanionsession")),
        migrations.AddField(model_name="aihelprequest", name="student", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_help_requests", to=settings.AUTH_USER_MODEL)),
    ]
