# Generated by Django 5.2.17 on 2026-09-01 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0037_essay_questions_and_manual_grading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='inactivity_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='inactivity_reminder_cooldown_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='recovery.competency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_misconceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competency__code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearnerMisconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Teacher confirmed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='detected', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('source_question_ids', models.JSONField(blank=True, default=list)),
                ('teacher_note', models.TextField(blank=True)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_misconception_signals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_signals', to=settings.AUTH_USER_MODEL)),
                ('misconception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_signals', to='recovery.misconception')),
            ],
            options={
                'ordering': ['-last_observed_at'],
            },
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='misconceptions',
            field=models.ManyToManyField(blank=True, related_name='practice_questions', to='recovery.misconception'),
        ),
        migrations.AddField(
            model_name='question',
            name='misconceptions',
            field=models.ManyToManyField(blank=True, related_name='assessment_questions', to='recovery.misconception'),
        ),
        migrations.CreateModel(
            name='AdaptiveLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('foundation', 'Foundation'), ('guided', 'Guided'), ('standard', 'Standard'), ('challenge', 'Challenge')], default='guided', max_length=16)),
                ('success_streak', models.PositiveSmallIntegerField(default=0)),
                ('miss_streak', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_learning_states', to='recovery.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_learning_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'competency'), name='unique_student_competency_adaptive_state')],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('target_score', models.PositiveSmallIntegerField(default=75)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('revised', 'Revised'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='recovery.competency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_goals', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='recovery.recoveryplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'target_date', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'competency'), name='unique_active_student_competency_goal')],
            },
        ),
        migrations.AddConstraint(
            model_name='misconception',
            constraint=models.UniqueConstraint(fields=('competency', 'code'), name='unique_competency_misconception_code'),
        ),
        migrations.AddConstraint(
            model_name='learnermisconception',
            constraint=models.UniqueConstraint(fields=('student', 'misconception'), name='unique_student_misconception_signal'),
        ),
    ]
