# Generated by Django 5.2.17 on 2026-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0038_companion_v2a'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cluster',
            field=models.CharField(choices=[('academics', 'Academics'), ('tech_pro', 'Tech Pro')], default='academics', max_length=16),
        ),
    ]
