import { useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useStudentScope } from '@/lib/student-scope';
import { colors, radius, spacing } from '@/constants/tokens';

export function StudentSubjectSwitcher() {
  const { subjects, selectedSubject, selectedSubjectId, setSelectedSubjectId } = useStudentScope();
  const [open, setOpen] = useState(false);
  if (!selectedSubject) return null;
  if (subjects.length === 1) return <View style={styles.single}><Text style={styles.singleText}>{selectedSubject.code}</Text></View>;
  return <><Pressable accessibilityRole="button" accessibilityLabel={`Learning subject: ${selectedSubject.name}`} onPress={() => setOpen(true)} style={styles.trigger}><Text style={styles.triggerText} numberOfLines={1}>{selectedSubject.code}</Text><Text style={styles.chevron}>⌄</Text></Pressable><Modal transparent visible={open} animationType="fade" onRequestClose={() => setOpen(false)}><Pressable style={styles.backdrop} onPress={() => setOpen(false)}><Pressable style={styles.sheet} onPress={event => event.stopPropagation()}><Text style={styles.heading}>Choose learning subject</Text><Text style={styles.description}>Progress, recovery activities, materials, and assessments will follow this subject.</Text>{subjects.map(subject => { const selected = subject.id === selectedSubjectId; return <Pressable key={subject.id} accessibilityRole="button" accessibilityState={{ selected }} onPress={() => { setSelectedSubjectId(subject.id); setOpen(false); }} style={[styles.row, selected && styles.selectedRow]}><View style={styles.rowText}><Text style={[styles.code, selected && styles.selectedText]}>{subject.code}</Text><Text style={[styles.name, selected && styles.selectedText]}>{subject.name}</Text><Text style={styles.meta}>Grade {subject.grade_level}</Text></View><Text style={[styles.action, selected && styles.selectedText]}>{selected ? 'Selected' : 'Choose'}</Text></Pressable>; })}<Pressable onPress={() => setOpen(false)} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable></Pressable></Pressable></Modal></>;
}

const styles = StyleSheet.create({ trigger: { maxWidth: 92, minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.control, paddingHorizontal: spacing.sm }, triggerText: { color: colors.primary, fontSize: 12, fontWeight: '800', flexShrink: 1 }, chevron: { color: colors.secondaryText, fontSize: 14 }, single: { minHeight: 34, justifyContent: 'center', paddingHorizontal: spacing.sm }, singleText: { color: colors.secondaryText, fontSize: 12, fontWeight: '800' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15, 23, 32, .38)' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.panel, borderTopRightRadius: radius.panel, padding: spacing.lg, paddingBottom: spacing.xxl, maxHeight: '80%' }, heading: { color: colors.text, fontSize: 20, fontWeight: '800' }, description: { color: colors.secondaryText, lineHeight: 19, marginTop: spacing.xs, marginBottom: spacing.lg }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md, paddingHorizontal: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, selectedRow: { backgroundColor: colors.primarySoft, borderLeftWidth: 3, borderLeftColor: colors.primary }, rowText: { flex: 1 }, code: { color: colors.secondaryText, fontSize: 11, fontWeight: '800' }, name: { color: colors.text, fontWeight: '700', lineHeight: 20, marginTop: 2 }, meta: { color: colors.secondaryText, fontSize: 12, marginTop: 2 }, selectedText: { color: colors.primary }, action: { color: colors.secondaryText, fontSize: 12, fontWeight: '700' }, cancel: { minHeight: 46, alignItems: 'center', justifyContent: 'center', marginTop: spacing.md }, cancelText: { color: colors.primary, fontWeight: '700' } });
