import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '@/lib/api';
import type { Assessment } from '@/lib/types';
import { colors, radius, spacing } from '@/constants/tokens';
import { useStudentScope } from '@/lib/student-scope';

export default function AssessmentsScreen() {
  const router = useRouter();
  const scope = useStudentScope();
  const [items, setItems] = useState<Assessment[] | null>(null);
  const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { if (!scope.selectedSubjectId) return; setItems(null); api<Assessment[] | { results?: Assessment[] }>(`/assessments/?subject=${scope.selectedSubjectId}`).then(result => setItems(Array.isArray(result) ? result : result.results ?? [])).catch(reason => setError(reason.message)); }, [scope.selectedSubjectId]));
  if (!scope.loading && !scope.selectedSubjectId) return <View style={styles.center}><Text style={styles.empty}>No subject with assigned assessments is available yet.</Text></View>;
  if (!items && !error) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.description}>Formal assessments cover target competencies and are separate from the short practice inside each lesson.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.list}>{items?.map(item => <Pressable key={item.id} disabled={!item.available} onPress={() => router.push({ pathname: '/assessment/[id]', params: { id: String(item.id) } })} style={({ pressed }) => [styles.row, pressed && styles.pressed, !item.available && styles.disabled]}><View style={styles.rowText}><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.kind === 'pre' ? 'Diagnostic assessment' : item.kind === 'remedial' ? 'Remedial exam' : 'Mastery assessment'} · {item.question_count} questions{item.due_at ? ` · Due ${new Date(item.due_at).toLocaleDateString()}` : ''}</Text>{!item.available && item.availability_reason ? <Text style={styles.reason}>{item.availability_reason}</Text> : null}</View><View style={[styles.status, item.available ? styles.available : styles.locked]}><Text style={[styles.statusText, item.available ? styles.availableText : styles.lockedText]}>{item.available ? 'Start' : 'Locked'}</Text></View></Pressable>)}</View>{!items?.length && <Text style={styles.empty}>No assessments are currently assigned.</Text>}</ScrollView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background }, description: { color: colors.secondaryText, lineHeight: 20, marginBottom: spacing.xl }, list: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel, overflow: 'hidden' }, row: { minHeight: 78, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, rowText: { flex: 1 }, title: { color: colors.text, fontWeight: '700' }, meta: { color: colors.secondaryText, fontSize: 12, lineHeight: 17, marginTop: spacing.xs }, reason: { color: colors.secondaryText, fontSize: 12, lineHeight: 17, marginTop: spacing.sm }, status: { borderRadius: radius.control, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, statusText: { fontSize: 12, fontWeight: '700' }, available: { backgroundColor: colors.primarySoft }, availableText: { color: colors.primary }, locked: { backgroundColor: '#eef0f2' }, lockedText: { color: colors.secondaryText }, disabled: { opacity: .72 }, pressed: { backgroundColor: colors.primarySoft }, empty: { color: colors.secondaryText, textAlign: 'center', marginTop: spacing.xl }, error: { color: colors.error, marginBottom: spacing.lg } });
