import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import type { Dashboard } from '@/lib/types';
import { colors, radius, spacing } from '@/constants/tokens';

export default function ProgressScreen() {
  const { user, signOut } = useAuth();
  const router = useRouter();
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { api<Dashboard>('/dashboard/student/').then(setData).catch(reason => setError(reason.message)); }, []));
  if (!data && !error) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  const active = data?.plans.find(plan => plan.status === 'active');
  const activityCount = active?.activities.length ?? 0;
  const completed = active?.activities.filter(item => item.completed_at).length ?? 0;
  const progress = activityCount ? Math.round(completed / activityCount * 100) : 0;
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.headingRow}><View><Text style={styles.eyebrow}>{user?.class_name ?? 'Student'}</Text><Text style={styles.title}>Hello, {user?.name.split(' ')[0]}</Text></View><Pressable onPress={() => void signOut()}><Text style={styles.link}>Sign out</Text></Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.summary}><Text style={styles.summaryLabel}>Current recovery focus</Text><Text style={styles.summaryTitle}>{active?.competency_title ?? 'No active recovery plan'}</Text><Text style={styles.summaryText}>{active ? `${completed} of ${activityCount} activities completed` : 'Your teacher will assign a plan when recovery support is needed.'}</Text>{active && <><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%` }]} /></View><Pressable style={styles.primaryButton} onPress={() => router.push('/(tabs)/recovery')}><Text style={styles.primaryButtonText}>Continue recovery plan</Text></Pressable></>}</View><View style={styles.metrics}><View style={styles.metric}><Text style={styles.metricValue}>{data?.mastered ?? 0}</Text><Text style={styles.metricLabel}>Competencies mastered</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{data?.total_competencies ?? 0}</Text><Text style={styles.metricLabel}>Competencies assigned</Text></View></View><View style={styles.section}><Text style={styles.sectionTitle}>Recent assessment results</Text>{data?.attempts.length ? data.attempts.slice(-3).reverse().map(attempt => <View key={attempt.id} style={styles.row}><View><Text style={styles.rowTitle}>Submitted assessment</Text><Text style={styles.meta}>{new Date(attempt.submitted_at).toLocaleDateString()}</Text></View><Text style={styles.score}>{Math.round(Number(attempt.score))}%</Text></View>) : <Text style={styles.empty}>No submitted assessments yet.</Text>}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.xl }, headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: colors.secondaryText, fontSize: 12, fontWeight: '600', textTransform: 'uppercase' }, title: { color: colors.text, fontSize: 26, fontWeight: '800', marginTop: spacing.xs }, link: { color: colors.primary, fontWeight: '700' }, summary: { backgroundColor: colors.primary, borderRadius: radius.panel, padding: spacing.xl }, summaryLabel: { color: '#c9dce6', fontSize: 12, fontWeight: '700', textTransform: 'uppercase' }, summaryTitle: { color: '#fff', fontSize: 20, fontWeight: '800', marginTop: spacing.sm }, summaryText: { color: '#dce9ef', lineHeight: 20, marginTop: spacing.sm }, progressTrack: { height: 7, backgroundColor: '#47758d', borderRadius: 4, overflow: 'hidden', marginTop: spacing.lg }, progressFill: { height: '100%', backgroundColor: '#fff' }, primaryButton: { backgroundColor: '#fff', minHeight: 44, borderRadius: radius.control, alignItems: 'center', justifyContent: 'center', marginTop: spacing.lg }, primaryButtonText: { color: colors.primary, fontWeight: '700' }, metrics: { flexDirection: 'row', gap: spacing.md }, metric: { flex: 1, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel, padding: spacing.lg }, metricValue: { color: colors.text, fontSize: 24, fontWeight: '800' }, metricLabel: { color: colors.secondaryText, fontSize: 12, lineHeight: 17, marginTop: spacing.xs }, section: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '700', padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, row: { minHeight: 64, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, rowTitle: { color: colors.text, fontWeight: '600' }, meta: { color: colors.secondaryText, fontSize: 12, marginTop: spacing.xs }, score: { color: colors.text, fontWeight: '800', fontSize: 17 }, empty: { color: colors.secondaryText, padding: spacing.xl, textAlign: 'center' }, error: { color: colors.error, backgroundColor: '#fef3f2', padding: spacing.md, borderRadius: radius.control } });
