import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { ActivityIndicator, Keyboard, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { colors, radius, spacing } from '@/constants/tokens';

type Profile = { name: string; email: string; role: string; class_name: string; assignments: string[]; preferred_name: string; phone: string; address_line: string; city_municipality: string; province: string; postal_code: string; identifier: string };

export default function ProfileScreen() {
  const { signOut, refreshUser } = useAuth();
  const [profile, setProfile] = useState<Profile | null>(null);
  const [form, setForm] = useState({ preferred_name: '', phone: '', address_line: '', city_municipality: '', province: '', postal_code: '' });
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const load = useCallback(() => { api<Profile>('/auth/profile/').then(value => { setProfile(value); setForm({ preferred_name: value.preferred_name, phone: value.phone, address_line: value.address_line, city_municipality: value.city_municipality, province: value.province, postal_code: value.postal_code }); }).catch(reason => setError(reason.message)); }, []);
  useFocusEffect(load);
  const save = async () => { Keyboard.dismiss(); setError(''); try { const updated = await api<Profile>('/auth/profile/', { method: 'PATCH', body: JSON.stringify(form) }); setProfile(updated); await refreshUser(); setMessage('Profile updated.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update profile.'); } };
  const changePassword = async () => { Keyboard.dismiss(); setError(''); try { await api('/auth/change-password/', { method: 'POST', body: JSON.stringify({ current_password: currentPassword, new_password: newPassword }) }); await signOut(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to change password.'); } };
  if (!profile && !error) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{error ? <Text style={styles.error}>{error}</Text> : null}{message ? <Text style={styles.success}>{message}</Text> : null}<View style={styles.card}><Text style={styles.title}>{profile?.name}</Text><Text style={styles.meta}>{profile?.email}</Text><Text style={styles.meta}>{profile?.identifier} · {profile?.class_name || 'Unassigned'}</Text></View><View style={styles.card}><Text style={styles.sectionTitle}>Personal details</Text><Field label="Preferred name" value={form.preferred_name} onChangeText={value => setForm(current => ({ ...current, preferred_name: value }))} /><Field label="Contact number" value={form.phone} onChangeText={value => setForm(current => ({ ...current, phone: value }))} /><Field label="Address" value={form.address_line} onChangeText={value => setForm(current => ({ ...current, address_line: value }))} /><Field label="City / municipality" value={form.city_municipality} onChangeText={value => setForm(current => ({ ...current, city_municipality: value }))} /><Field label="Province" value={form.province} onChangeText={value => setForm(current => ({ ...current, province: value }))} /><Field label="Postal code" value={form.postal_code} onChangeText={value => setForm(current => ({ ...current, postal_code: value }))} /><Pressable style={styles.primary} onPress={() => void save()}><Text style={styles.primaryText}>Save profile</Text></Pressable></View><View style={styles.card}><Text style={styles.sectionTitle}>Change password</Text><Field label="Current password" value={currentPassword} onChangeText={setCurrentPassword} secureTextEntry /><Field label="New password" value={newPassword} onChangeText={setNewPassword} secureTextEntry /><Pressable disabled={!currentPassword || newPassword.length < 8} style={[styles.secondary, (!currentPassword || newPassword.length < 8) && styles.disabled]} onPress={() => void changePassword()}><Text style={styles.secondaryText}>Change password and sign out</Text></Pressable></View><Pressable onPress={() => void signOut()} style={styles.signOut}><Text style={styles.signOutText}>Sign out</Text></Pressable></ScrollView>;
}

function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; secureTextEntry?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xxl }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel, padding: spacing.lg, gap: spacing.md }, title: { color: colors.text, fontSize: 22, fontWeight: '800' }, sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' }, meta: { color: colors.secondaryText }, field: { gap: spacing.xs }, label: { color: colors.secondaryText, fontSize: 12, fontWeight: '700' }, input: { minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: radius.control, paddingHorizontal: spacing.md, color: colors.text, backgroundColor: '#fff' }, primary: { minHeight: 46, backgroundColor: colors.primary, borderRadius: radius.control, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#fff', fontWeight: '700' }, secondary: { minHeight: 46, borderWidth: 1, borderColor: colors.primary, borderRadius: radius.control, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.primary, fontWeight: '700' }, disabled: { opacity: .45 }, signOut: { minHeight: 48, alignItems: 'center', justifyContent: 'center' }, signOutText: { color: colors.error, fontWeight: '700' }, error: { color: colors.error, backgroundColor: '#fef3f2', padding: spacing.md, borderRadius: radius.control }, success: { color: colors.success, backgroundColor: '#edf8f2', padding: spacing.md, borderRadius: radius.control } });
