import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '@/lib/api';
import type { Plan } from '@/lib/types';
import { colors, radius, spacing } from '@/constants/tokens';

export default function RecoveryScreen() {
  const router = useRouter();
  const [plans, setPlans] = useState<Plan[] | null>(null);
  const [selectedPlanId, setSelectedPlanId] = useState<number | null>(null);
  const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { api<Plan[] | { results?: Plan[] }>('/recovery-plans/').then(result => { const found = Array.isArray(result) ? result : result.results ?? []; setPlans(found); setSelectedPlanId(current => current ?? found.find(item => item.status === 'active')?.id ?? found[0]?.id ?? null); }).catch(reason => setError(reason.message)); }, []));
  if (!plans && !error) return <View style={styles.center}><ActivityIndicator color={colors.primary} /></View>;
  const plan = plans?.find(item => item.id === selectedPlanId) ?? plans?.find(item => item.status === 'active') ?? plans?.[0];
  if (!plan) return <View style={styles.center}><Text style={styles.emptyTitle}>No recovery plan</Text><Text style={styles.emptyText}>Complete an assigned diagnostic assessment first.</Text></View>;
  const canOpen = (position: number) => !plan.activities.some(item => item.position < position && !item.completed_at);
  const allResources = (plans ?? []).flatMap(item => item.activities.filter(activity => activity.resource));
  const allCompleted = allResources.filter(activity => activity.completed_at).length;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>{plans && plans.length > 1 && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.planTabs}>{plans.map(item => { const resources = item.activities.filter(activity => activity.resource); const done = resources.filter(activity => activity.completed_at).length; const selected = item.id === plan.id; return <Pressable key={item.id} onPress={() => setSelectedPlanId(item.id)} style={[styles.planTab, selected && styles.selectedPlanTab]}><Text style={[styles.planTabTitle, selected && styles.selectedPlanTabTitle]} numberOfLines={1}>{item.competency_title}</Text><Text style={styles.planTabMeta}>{item.status === 'completed' ? 'Mastered' : `${done} of ${resources.length} activities`}</Text></Pressable>; })}</ScrollView>}<View style={styles.overall}><Text style={styles.overallTitle}>Overall recovery progress</Text><Text style={styles.overallMeta}>{allCompleted} of {allResources.length} activities completed · {allResources.length - allCompleted} remaining</Text></View><Text style={styles.eyebrow}>Current competency</Text><Text style={styles.title}>{plan.competency_title}</Text><Text style={styles.description}>Complete activities in order. Practice answers are checked before progress is recorded.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.list}>{plan.activities.map((activity, index) => { const unlocked = canOpen(activity.position); const masteryReady = Boolean(plan.mastery_assessment?.available); const actionable = unlocked && (Boolean(activity.resource) || masteryReady); const open = () => activity.resource ? router.push({ pathname: '/activity/[id]', params: { id: String(activity.id), planId: String(plan.id) } }) : router.push('/(tabs)/assessments'); return <Pressable key={activity.id} disabled={!actionable} onPress={open} style={({ pressed }) => [styles.activity, pressed && styles.pressed, !actionable && styles.locked]}><View style={[styles.number, activity.completed_at && styles.completedNumber]}><Text style={[styles.numberText, activity.completed_at && styles.completedNumberText]}>{activity.completed_at ? '✓' : index + 1}</Text></View><View style={styles.activityText}><Text style={styles.activityTitle}>{activity.title}</Text><Text style={styles.meta}>{activity.completed_at ? 'Completed' : !unlocked ? 'Locked' : activity.resource ? activity.due_at ? `Due ${new Date(activity.due_at).toLocaleDateString()}` : 'Available' : plan.mastery_assessment?.available ? 'Open mastery assessment' : plan.mastery_assessment?.availability_reason ?? 'No mastery assessment assigned'}</Text></View><Text style={styles.chevron}>{actionable ? '›' : ''}</Text></Pressable>; })}</View></ScrollView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl, backgroundColor: colors.background }, planTabs: { gap: spacing.sm, paddingBottom: spacing.lg }, planTab: { width: 210, borderWidth: 1, borderColor: colors.border, borderRadius: radius.control, padding: spacing.md, backgroundColor: colors.surface }, selectedPlanTab: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, planTabTitle: { color: colors.text, fontWeight: '700' }, selectedPlanTabTitle: { color: colors.primary }, planTabMeta: { color: colors.secondaryText, fontSize: 12, marginTop: spacing.xs }, overall: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.control, backgroundColor: colors.surface, padding: spacing.md, marginBottom: spacing.xl }, overallTitle: { color: colors.text, fontWeight: '700' }, overallMeta: { color: colors.secondaryText, fontSize: 12, marginTop: spacing.xs }, eyebrow: { color: colors.primary, fontSize: 12, textTransform: 'uppercase', fontWeight: '700' }, title: { color: colors.text, fontSize: 23, fontWeight: '800', marginTop: spacing.sm }, description: { color: colors.secondaryText, lineHeight: 20, marginTop: spacing.sm, marginBottom: spacing.xl }, list: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.panel, overflow: 'hidden' }, activity: { minHeight: 76, flexDirection: 'row', alignItems: 'center', padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, number: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: spacing.md }, completedNumber: { backgroundColor: colors.success, borderColor: colors.success }, numberText: { color: colors.primary, fontWeight: '700' }, completedNumberText: { color: '#fff' }, activityText: { flex: 1 }, activityTitle: { color: colors.text, fontWeight: '700' }, meta: { color: colors.secondaryText, fontSize: 12, lineHeight: 17, marginTop: spacing.xs }, chevron: { color: colors.secondaryText, fontSize: 24 }, locked: { opacity: .62 }, pressed: { backgroundColor: colors.primarySoft }, emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '700' }, emptyText: { color: colors.secondaryText, textAlign: 'center', marginTop: spacing.sm }, error: { color: colors.error, marginBottom: spacing.lg } });
