import { useEffect, useState } from 'react';
import { Alert, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { Add, ArrowBack, ChevronRight, EditOutlined } from '@mui/icons-material';
import { api } from '../api/client';
import type { ApiCompetency, ApiSubject } from '../api/types';
import { DataTablePagination, DataTableToolbar, SortableTableCell, useServerTable } from '../components/DataTable';
import { PageHeader } from '../components/PageHeader';
import { StatusChip } from '../components/StatusChip';

export function SubjectsPage({ onOpenCompetencies }: { onOpenCompetencies: (subjectId: number) => void }) {
  const [grade, setGrade] = useState('');
  const [status, setStatus] = useState('');
  const [editor, setEditor] = useState<ApiSubject | null | undefined>();
  const [form, setForm] = useState({ name: '', code: '', grade_level: 11, is_active: true });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const table = useServerTable<ApiSubject>({ path: '/subjects/', initialSort: 'name', extraParams: `${grade ? `grade=${grade}` : ''}${status ? `${grade ? '&' : ''}status=${status}` : ''}` });
  const open = (item?: ApiSubject) => { setEditor(item ?? null); setForm(item ? { name: item.name, code: item.code, grade_level: item.grade_level, is_active: item.is_active } : { name: '', code: '', grade_level: 11, is_active: true }); };
  const save = async () => {
    try { await api(editor ? `/subjects/${editor.id}/` : '/subjects/', { method: editor ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setEditor(undefined); setMessage(editor ? 'Subject updated.' : 'Subject created.'); table.reload(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save this subject.'); }
  };
  return <>
    <PageHeader title="Subjects" description="Manage Grade 11 and Grade 12 subjects. Open a subject to maintain its competencies." action={<Button variant="contained" startIcon={<Add />} onClick={() => open()}>Add Subject</Button>} />
    {(error || table.error) && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error || table.error}</Alert>}{message && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setMessage('')}>{message}</Alert>}
    <Card><DataTableToolbar query={table.query} onQuery={table.setQuery} placeholder="Search subjects" count={table.count} actions={<Stack direction="row" gap={1}><TextField select size="small" label="Grade" value={grade} onChange={event => setGrade(event.target.value)} sx={{ width: 125 }}><MenuItem value="">All grades</MenuItem><MenuItem value="11">Grade 11</MenuItem><MenuItem value="12">Grade 12</MenuItem></TextField><TextField select size="small" label="Status" value={status} onChange={event => setStatus(event.target.value)} sx={{ width: 120 }}><MenuItem value="">All</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="archived">Archived</MenuItem></TextField></Stack>} /><Divider />
      <TableContainer><Table sx={{ minWidth: 760 }}><TableHead><TableRow><SortableTableCell column="code" label="Code" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><SortableTableCell column="name" label="Subject" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><TableCell>Grade</TableCell><SortableTableCell column="competencies" label="Competencies" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><SortableTableCell column="status" label="Status" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{table.rows.map(item => <TableRow key={item.id} hover><TableCell>{item.code}</TableCell><TableCell><Button onClick={() => onOpenCompetencies(item.id)} endIcon={<ChevronRight />} sx={{ justifyContent: 'flex-start', px: 0, fontWeight: 700, textAlign: 'left' }}>{item.name}</Button></TableCell><TableCell>Grade {item.grade_level}</TableCell><TableCell>{item.competency_count}</TableCell><TableCell><StatusChip label={item.is_active ? 'Active' : 'Archived'} /></TableCell><TableCell align="right"><Button size="small" startIcon={<EditOutlined />} onClick={() => open(item)}>Edit</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>
      {!table.loading && !table.count && <Typography variant="body2" color="text.secondary" sx={{ p: 4, textAlign: 'center' }}>No subjects match the current filters.</Typography>}<DataTablePagination count={table.count} page={table.page} rowsPerPage={table.rowsPerPage} onPage={table.setPage} onRowsPerPage={table.setRowsPerPage} />
    </Card>
    <Dialog component="form" open={editor !== undefined} onClose={() => setEditor(undefined)} onSubmit={event => { event.preventDefault(); void save(); }} fullWidth maxWidth="sm"><DialogTitle>{editor ? 'Edit Subject' : 'Add Subject'}</DialogTitle><DialogContent><Stack gap={2} sx={{ pt: 1 }}><TextField label="Subject Name" value={form.name} onChange={event => setForm(value => ({ ...value, name: event.target.value }))} required autoFocus /><TextField label="Subject Code" value={form.code} onChange={event => setForm(value => ({ ...value, code: event.target.value.toUpperCase() }))} required /><TextField select label="Grade Level" value={form.grade_level} onChange={event => setForm(value => ({ ...value, grade_level: Number(event.target.value) }))}><MenuItem value={11}>Grade 11</MenuItem><MenuItem value={12}>Grade 12</MenuItem></TextField><TextField select label="Status" value={form.is_active ? 'active' : 'archived'} onChange={event => setForm(value => ({ ...value, is_active: event.target.value === 'active' }))}><MenuItem value="active">Active</MenuItem><MenuItem value="archived">Archived</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={() => setEditor(undefined)}>Cancel</Button><Button type="submit" variant="contained">Save Subject</Button></DialogActions></Dialog>
  </>;
}

export function CompetenciesPage({ subjectId, onBack }: { subjectId: number; onBack: () => void }) {
  const [subject, setSubject] = useState<ApiSubject | null>(null);
  const [status, setStatus] = useState('');
  const [editor, setEditor] = useState<ApiCompetency | null | undefined>();
  const [form, setForm] = useState({ code: '', title: '', mastery_threshold: 75, is_active: true });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const table = useServerTable<ApiCompetency>({ path: '/competencies/', initialSort: 'code', extraParams: `subject=${subjectId}${status ? `&status=${status}` : ''}` });
  useEffect(() => { api<ApiSubject>(`/subjects/${subjectId}/`).then(setSubject).catch(reason => setError(reason.message)); }, [subjectId]);
  const open = (item?: ApiCompetency) => { setEditor(item ?? null); setForm(item ? { code: item.code, title: item.title, mastery_threshold: item.mastery_threshold, is_active: item.is_active } : { code: '', title: '', mastery_threshold: 75, is_active: true }); };
  const save = async () => {
    try { await api(editor ? `/competencies/${editor.id}/` : '/competencies/', { method: editor ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, subject: subjectId }) }); setEditor(undefined); setMessage(editor ? 'Competency updated.' : 'Competency created.'); table.reload(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save this competency.'); }
  };
  return <>
    <Button startIcon={<ArrowBack />} onClick={onBack} sx={{ mb: 1.5 }}>Back to Subjects</Button>
    <PageHeader title={subject ? `${subject.name} Competencies` : 'Competencies'} description={subject ? `${subject.code} · Grade ${subject.grade_level}. These competencies drive assessments, recovery plans, and recommendations.` : 'Loading subject…'} action={<Button variant="contained" startIcon={<Add />} onClick={() => open()} disabled={!subject}>Add Competency</Button>} />
    {(error || table.error) && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error || table.error}</Alert>}{message && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setMessage('')}>{message}</Alert>}
    <Card><DataTableToolbar query={table.query} onQuery={table.setQuery} placeholder="Search competencies" count={table.count} actions={<TextField select size="small" label="Status" value={status} onChange={event => setStatus(event.target.value)} sx={{ width: 120 }}><MenuItem value="">All</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="archived">Archived</MenuItem></TextField>} /><Divider /><TableContainer><Table sx={{ minWidth: 720 }}><TableHead><TableRow><SortableTableCell column="code" label="Code" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><SortableTableCell column="title" label="Competency" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><SortableTableCell column="threshold" label="Mastery Threshold" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><SortableTableCell column="status" label="Status" orderBy={table.orderBy} direction={table.direction} onSort={table.toggleSort} /><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{table.rows.map(item => <TableRow key={item.id} hover><TableCell>{item.code}</TableCell><TableCell><Typography variant="body2" fontWeight={650}>{item.title}</Typography></TableCell><TableCell>{item.mastery_threshold}%</TableCell><TableCell><StatusChip label={item.is_active ? 'Active' : 'Archived'} /></TableCell><TableCell align="right"><Button size="small" startIcon={<EditOutlined />} onClick={() => open(item)}>Edit</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>{!table.loading && !table.count && <Typography variant="body2" color="text.secondary" sx={{ p: 4, textAlign: 'center' }}>No competencies match the current filters.</Typography>}<DataTablePagination count={table.count} page={table.page} rowsPerPage={table.rowsPerPage} onPage={table.setPage} onRowsPerPage={table.setRowsPerPage} /></Card>
    <Dialog component="form" open={editor !== undefined} onClose={() => setEditor(undefined)} onSubmit={event => { event.preventDefault(); void save(); }} fullWidth maxWidth="sm"><DialogTitle>{editor ? 'Edit Competency' : 'Add Competency'}</DialogTitle><DialogContent><Stack gap={2} sx={{ pt: 1 }}><TextField label="Competency Code" value={form.code} onChange={event => setForm(value => ({ ...value, code: event.target.value.toUpperCase() }))} required autoFocus /><TextField label="Competency" value={form.title} onChange={event => setForm(value => ({ ...value, title: event.target.value }))} multiline minRows={2} required /><TextField label="Mastery Threshold" type="number" value={form.mastery_threshold} onChange={event => setForm(value => ({ ...value, mastery_threshold: Number(event.target.value) }))} inputProps={{ min: 1, max: 100 }} required /><TextField select label="Status" value={form.is_active ? 'active' : 'archived'} onChange={event => setForm(value => ({ ...value, is_active: event.target.value === 'active' }))}><MenuItem value="active">Active</MenuItem><MenuItem value="archived">Archived</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={() => setEditor(undefined)}>Cancel</Button><Button type="submit" variant="contained">Save Competency</Button></DialogActions></Dialog>
  </>;
}
