import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, Divider, LinearProgress, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, Typography } from '@mui/material';
import { api } from '../api/client';
import type { ApiLearner, MaterialAnalytics } from '../api/types';
import { DataTablePagination, DataTableToolbar, SortableTableCell, useDataTable } from '../components/DataTable';
import { PageHeader } from '../components/PageHeader';
import { StatusChip } from '../components/StatusChip';
import { downloadText } from '../utils/download';
import { useTeachingScope } from '../components/TeachingScopeContext';

export function TeacherReportsPage() {
  const [learners, setLearners] = useState<ApiLearner[]>([]);
  const [materials, setMaterials] = useState<MaterialAnalytics | null>(null);
  const [section, setSection] = useState<'recovery' | 'materials'>('recovery');
  const [error, setError] = useState('');
  const scope = useTeachingScope();
  useEffect(() => { if (!scope?.selectedSubjectId) return; setError(''); Promise.all([api<ApiLearner[]>(`/dashboard/teacher/learners/?subject=${scope.selectedSubjectId}`), api<MaterialAnalytics>(`/dashboard/teacher/materials/?subject=${scope.selectedSubjectId}`)]).then(([learnerRows, materialRows]) => { setLearners(learnerRows); setMaterials(materialRows); }).catch(reason => setError(reason.message)); }, [scope?.selectedSubjectId]);
  const recoveryTable = useDataTable(learners, { searchText: item => `${item.name} ${item.email} ${item.section} ${item.status}`, sortValues: { learner: item => item.name, progress: item => item.progress, gaps: item => item.gaps, score: item => item.assessment, status: item => item.status }, initialSort: 'gaps', initialDirection: 'desc' });
  const materialTable = useDataTable(materials?.learners ?? [], { searchText: item => `${item.material} ${item.student} ${item.section} ${item.status}`, sortValues: { material: item => item.material, learner: item => item.student, status: item => item.status, progress: item => item.progress_percent, score: item => item.latest_quiz_score, activity: item => item.last_activity_at ? new Date(item.last_activity_at).getTime() : 0 }, initialSort: 'activity', initialDirection: 'desc' });
  const assessed = learners.filter(item => item.assessment !== null);
  const exportReport = () => section === 'materials'
    ? downloadText('tala-material-engagement.csv', ['Material,Learner,Section,Status,Reading progress,Latest quiz score,Attempts,Quiz passed', ...(materials?.learners ?? []).map(item => `"${item.material}","${item.student}","${item.section}",${item.status},${item.progress_percent}%,${item.latest_quiz_score ?? ''},${item.attempt_count},${item.quiz_passed ? 'Yes' : 'No'}`)].join('\n'))
    : downloadText('tala-recovery-report.csv', ['Learner,Plan progress,Active gaps,Latest assessment,Status', ...learners.map(item => `${item.name},${item.progress}%,${item.gaps},${item.assessment ?? ''},${item.status}`)].join('\n'));
  return <>
    <PageHeader title="Reports & Analytics" description="Review assessment outcomes, recovery progress, material engagement, and module quiz results." action={<Button variant="outlined" onClick={exportReport}>Export Current View</Button>} />
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Card sx={{ mb: 3 }}><Tabs value={section} onChange={(_, value) => setSection(value)}><Tab value="recovery" label="Recovery Outcomes" /><Tab value="materials" label="Learning Materials & Quizzes" /></Tabs></Card>
    {section === 'recovery' ? <>
      <Card sx={{ mb: 3, p: 2.5 }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', lg: 'repeat(4, 1fr)' }, gap: { xs: 2, lg: 0 } }}>{[['Learners', learners.length], ['Assessed', assessed.length], ['Average Score', assessed.length ? `${Math.round(assessed.reduce((sum, item) => sum + Number(item.assessment), 0) / assessed.length)}%` : '—'], ['Average Plan Progress', learners.length ? `${Math.round(learners.reduce((sum, item) => sum + item.progress, 0) / learners.length)}%` : '—']].map(([label, value], index) => <Box key={label} sx={{ px: { lg: index === 0 ? 0 : 3 }, borderLeft: { lg: index > 0 ? '1px solid #e1e6eb' : 0 } }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography sx={{ fontSize: 24, fontWeight: 750 }}>{value}</Typography></Box>)}</Box></Card>
      <Card><DataTableToolbar query={recoveryTable.query} onQuery={recoveryTable.setQuery} placeholder="Search learner outcomes" count={recoveryTable.filteredCount} /><TableContainer><Table sx={{ minWidth: 720 }}><TableHead><TableRow><SortableTableCell column="learner" label="Learner" orderBy={recoveryTable.orderBy} direction={recoveryTable.direction} onSort={recoveryTable.toggleSort} /><SortableTableCell column="progress" label="Plan Progress" orderBy={recoveryTable.orderBy} direction={recoveryTable.direction} onSort={recoveryTable.toggleSort} /><SortableTableCell column="gaps" label="Active Gaps" orderBy={recoveryTable.orderBy} direction={recoveryTable.direction} onSort={recoveryTable.toggleSort} /><SortableTableCell column="score" label="Latest Score" orderBy={recoveryTable.orderBy} direction={recoveryTable.direction} onSort={recoveryTable.toggleSort} /><SortableTableCell column="status" label="Status" orderBy={recoveryTable.orderBy} direction={recoveryTable.direction} onSort={recoveryTable.toggleSort} /></TableRow></TableHead><TableBody>{recoveryTable.pageRows.map(item => <TableRow key={item.id}><TableCell><Typography variant="body2" fontWeight={700}>{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.section}</Typography></TableCell><TableCell><Stack direction="row" alignItems="center" gap={1}><LinearProgress variant="determinate" value={item.progress} sx={{ width: 100, height: 6 }} /><Typography variant="caption">{item.progress}%</Typography></Stack></TableCell><TableCell>{item.gaps}</TableCell><TableCell>{item.assessment === null ? '—' : `${Math.round(item.assessment)}%`}</TableCell><TableCell><StatusChip label={item.status} /></TableCell></TableRow>)}</TableBody></Table></TableContainer><DataTablePagination count={recoveryTable.filteredCount} page={recoveryTable.page} rowsPerPage={recoveryTable.rowsPerPage} onPage={recoveryTable.setPage} onRowsPerPage={recoveryTable.setRowsPerPage} /></Card>
    </> : <>
      <Card sx={{ mb: 3, p: 2.5 }}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', lg: 'repeat(5, 1fr)' }, gap: { xs: 2, lg: 0 } }}>{[['Materials', materials?.summary.materials ?? 0], ['Learner Assignments', materials?.summary.assigned_learners ?? 0], ['Currently Reading', materials?.summary.in_progress ?? 0], ['Completed', materials?.summary.completed ?? 0], ['Quiz Passed', materials?.summary.quiz_passed ?? 0]].map(([label, value], index) => <Box key={label} sx={{ px: { lg: index === 0 ? 0 : 3 }, borderLeft: { lg: index > 0 ? '1px solid #e1e6eb' : 0 } }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography sx={{ fontSize: 24, fontWeight: 750 }}>{value}</Typography></Box>)}</Box></Card>
      <Card sx={{ mb: 3 }}><Box sx={{ p: 2.5 }}><Typography variant="h2">Material Performance</Typography><Typography variant="body2" color="text.secondary">Completion and quiz outcomes by uploaded module or video.</Typography></Box><Divider /><Stack divider={<Divider />}>{materials?.materials.map(item => <Box key={item.id} sx={{ p: 2.5, display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', md: 'minmax(260px, 1fr) repeat(5, minmax(80px, auto))' }, gap: 2 }}><Box><Typography variant="body2" fontWeight={700}>{item.title}</Typography><Typography variant="caption" color="text.secondary">{item.quiz_question_count} quiz questions · {item.assigned} assigned learners</Typography></Box>{[['Not Started', item.not_started], ['Reading', item.in_progress], ['Completed', item.completed], ['Quiz Passed', item.quiz_passed], ['Average Score', item.average_quiz_score === null ? '—' : `${item.average_quiz_score}%`]].map(([label, value]) => <Box key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={700}>{value}</Typography></Box>)}</Box>)}</Stack>{!materials?.materials.length && <Typography variant="body2" color="text.secondary" sx={{ p: 3 }}>No learning materials have been assigned by this teacher.</Typography>}</Card>
      <Card><Box sx={{ p: 2.5 }}><Typography variant="h2">Learner Material Activity</Typography><Typography variant="body2" color="text.secondary">See who has not started, is currently reading, completed, or passed a quiz.</Typography></Box><Divider /><DataTableToolbar query={materialTable.query} onQuery={materialTable.setQuery} placeholder="Search learner or material" count={materialTable.filteredCount} /><TableContainer><Table sx={{ minWidth: 900 }}><TableHead><TableRow><SortableTableCell column="material" label="Material" orderBy={materialTable.orderBy} direction={materialTable.direction} onSort={materialTable.toggleSort} /><SortableTableCell column="learner" label="Learner" orderBy={materialTable.orderBy} direction={materialTable.direction} onSort={materialTable.toggleSort} /><SortableTableCell column="status" label="Status" orderBy={materialTable.orderBy} direction={materialTable.direction} onSort={materialTable.toggleSort} /><SortableTableCell column="progress" label="Reading Progress" orderBy={materialTable.orderBy} direction={materialTable.direction} onSort={materialTable.toggleSort} /><SortableTableCell column="score" label="Latest Quiz" orderBy={materialTable.orderBy} direction={materialTable.direction} onSort={materialTable.toggleSort} /><TableCell>Attempts</TableCell></TableRow></TableHead><TableBody>{materialTable.pageRows.map(item => <TableRow key={`${item.assignment_id}-${item.student_id}`}><TableCell><Typography variant="body2" fontWeight={650}>{item.material}</Typography></TableCell><TableCell><Typography variant="body2">{item.student}</Typography><Typography variant="caption" color="text.secondary">{item.section}</Typography></TableCell><TableCell><StatusChip label={item.status.replace('_', ' ')} /></TableCell><TableCell>{item.resource_type === 'video' ? `${item.progress_percent}%` : item.status === 'in_progress' ? 'Opened' : item.status === 'completed' ? 'Completed' : 'Not opened'}</TableCell><TableCell>{item.latest_quiz_score === null ? 'Not attempted' : <><Typography variant="body2" fontWeight={700}>{Math.round(item.latest_quiz_score)}%</Typography><Typography variant="caption" color={item.quiz_passed ? 'success.main' : 'error.main'}>{item.quiz_passed ? 'Passed' : 'Needs retry'}</Typography></>}</TableCell><TableCell>{item.attempt_count}</TableCell></TableRow>)}</TableBody></Table></TableContainer><DataTablePagination count={materialTable.filteredCount} page={materialTable.page} rowsPerPage={materialTable.rowsPerPage} onPage={materialTable.setPage} onRowsPerPage={materialTable.setRowsPerPage} /></Card>
    </>}
  </>;
}
